const API_URL='https://script.google.com/macros/s/AKfycbx6DLeZ_svRlYYltAyqjvDLlS_hWoaXlNpl5toWMSwxBnc-XljdLRrr1cKISzeS-HMt/exec';
const $=id=>document.getElementById(id), startCard=$('startCard'), endCard=$('endCard'), successCard=$('successCard'), startForm=$('startForm'), endForm=$('endForm'), toast=$('toast');
let activeTrip=null,toastTimer;
function nowParts(){const now=new Date();return{date:new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Asia/Kolkata'}).format(now),time:new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true,timeZone:'Asia/Kolkata'}).format(now)}}
function numberValue(id){const v=parseFloat($(id).value);return Number.isFinite(v)?v:0}
function showToast(message,isError=false){clearTimeout(toastTimer);toast.textContent=message;toast.className=`toast show${isError?' error':''}`;toastTimer=setTimeout(()=>toast.className='toast',3500)}
function setProgress(stage){$('stepStart').classList.toggle('active',stage==='start');$('stepEnd').classList.toggle('active',stage==='end')}
function updateClockFields(){const p=nowParts();if(!activeTrip){$('date').value=p.date;$('startTime').value=p.time}else $('endTime').value=p.time}
function saveActiveTrip(trip){activeTrip=trip;sessionStorage.setItem('viaActiveTrip',JSON.stringify(trip))}
function loadActiveTrip(){try{const saved=JSON.parse(sessionStorage.getItem('viaActiveTrip')||'null');if(saved&&saved.driver&&saved.vehicle&&Number.isFinite(Number(saved.startKM))){activeTrip=saved;showEndTrip()}}catch(_){sessionStorage.removeItem('viaActiveTrip')}}
function showEndTrip(){$('activeDriver').textContent=activeTrip.driver;$('activeVehicle').textContent=activeTrip.vehicle;$('activeStart').textContent=`${activeTrip.date} · ${activeTrip.startTime}`;updateClockFields();startCard.classList.add('hidden');endCard.classList.remove('hidden');successCard.classList.add('hidden');setProgress('end')}
function showStartTrip(){activeTrip=null;sessionStorage.removeItem('viaActiveTrip');startForm.reset();endForm.reset();updateClockFields();startCard.classList.remove('hidden');endCard.classList.add('hidden');successCard.classList.add('hidden');setProgress('start');$('driver').focus()}
function updateSummary(){const start=activeTrip?Number(activeTrip.startKM):0,end=numberValue('endKM'),km=Math.max(0,end-start),collection=numberValue('collection'),cng=numberValue('cngCost'),toll=numberValue('toll'),other=numberValue('otherExpense'),litres=numberValue('cngLitres'),net=collection-cng-toll-other,perKm=km>0?collection/km:0,kmPerLitre=litres>0?km/litres:0;$('totalKM').textContent=km.toFixed(1);$('netCollection').textContent=`₹${net.toLocaleString('en-IN',{maximumFractionDigits:2})}`;$('collectionPerKM').textContent=`₹${perKm.toFixed(2)}`;$('kmPerLitre').textContent=kmPerLitre.toFixed(2);return{km,net,perKm,kmPerLitre}}
$('endKM').addEventListener('input',updateSummary);['collection','cngCost','cngLitres','toll','otherExpense'].forEach(id=>$(id).addEventListener('input',updateSummary));
startForm.addEventListener('submit',async e=>{e.preventDefault();const driver=$('driver').value.trim(),vehicle=$('vehicle').value.trim().toUpperCase(),startKM=Number($('startKM').value),p=nowParts();if(!driver)return showToast('Please enter your name.',true);if(!vehicle)return showToast('Please enter the vehicle number.',true);if(!Number.isFinite(startKM)||startKM<0)return showToast('Enter a valid start odometer.',true);const trip={driver,vehicle,startKM,date:p.date,startTime:p.time},button=startForm.querySelector('button');button.disabled=true;button.innerHTML='Starting…';try{const params=new URLSearchParams({action:'start',driver,vehicle,date:trip.date,startTime:trip.startTime,startKM:String(startKM)});await fetch(API_URL,{method:'POST',mode:'no-cors',body:params});saveActiveTrip(trip);showEndTrip();showToast('Trip started. Drive safe!')}catch(_){showToast('Could not connect. Please try again.',true)}finally{button.disabled=false;button.innerHTML='Start Trip <span>→</span>'}});
endForm.addEventListener('submit',async e=>{e.preventDefault();if(!activeTrip)return showToast('No active trip found.',true);const endKM=Number($('endKM').value);if(!Number.isFinite(endKM)||endKM<activeTrip.startKM)return showToast('End KM must be equal to or higher than Start KM.',true);const summary=updateSummary(),button=$('submitEndBtn'),p=nowParts();button.disabled=true;button.innerHTML='Saving…';$('endTime').value=p.time;const payload={action:'end',driver:activeTrip.driver,vehicle:activeTrip.vehicle,endTime:p.time,endKM:String(endKM),collection:String(numberValue('collection')),cngCost:String(numberValue('cngCost')),cngLitres:String(numberValue('cngLitres')),toll:String(numberValue('toll')),otherExpense:String(numberValue('otherExpense')),paymentType:$('paymentType').value,remarks:$('remarks').value};try{await fetch(API_URL,{method:'POST',mode:'no-cors',body:new URLSearchParams(payload)});sessionStorage.removeItem('viaActiveTrip');activeTrip=null;endCard.classList.add('hidden');successCard.classList.remove('hidden');setProgress('end');showToast(`Saved · ${summary.km.toFixed(1)} KM`)}catch(_){showToast('Could not save the trip. Please try again.',true)}finally{button.disabled=false;button.innerHTML='Submit Trip <span>✓</span>'}});
$('newTripBtn').addEventListener('click',showStartTrip);setInterval(updateClockFields,30000);updateClockFields();loadActiveTrip();
